language: node_js
node_js:
  - 8
sudo: false
matrix:
  include:
    # testing the ^15.x releases
    - env: REACT_VERSION=^15.x
    # testing the ^16.x releases
    - env: REACT_VERSION=^16.x
    # testing the latest release
    - env: REACT_VERSION=latest
cache: yarn
install:
  - yarn
  - yarn add react@$REACT_VERSION react-dom@$REACT_VERSION
notifications:
  email: false
after_success:
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
