language: node_js
node_js:
  - "stable"
sudo: false
matrix:
  include:
    # testing the ^15.x releases
    - env: REACT_VERSION=^15.x
    # testing the ^16.x releases
    - env: REACT_VERSION=^16.x
    # testing the latest release
    - env: REACT_VERSION=latest
cache: yarn
install:
  - yarn
  - yarn add react@$REACT_VERSION react-dom@$REACT_VERSION
